services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: quail_db
      POSTGRES_USER: quail_user
      POSTGRES_PASSWORD: quail_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d
    networks:
      - quail_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quail_user -d quail_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NestJS API - Development with hot reload
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://quail_user:quail_password@postgres:5432/quail_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      NODE_ENV: development
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quail_network
    restart: unless-stopped
    command: npm run start:dev

  # Angular Frontend - Development with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - quail_network
    command: npm start -- --host 0.0.0.0 --poll 2000

  # Ollama for LLM management
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - quail_network

volumes:
  postgres_data:
  ollama_data:

networks:
  quail_network:
    driver: bridge 